<a href="https://colab.research.google.com/github/Rezki-Ramzi/Deep-learning-/blob/main/PhocNet_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# la taille de vecteur phoc est 604 
# word : chaine de caracters
bigram = ['th', 'he', 'in', 'er', 'an', 're', 'es', 'on', 'st', 'nt', 'en',
'at', 'ed', 'nd', 'to', 'or', 'ea', 'ti', 'ar', 'te', 'ng', 'al',
'it', 'as', 'is', 'ha', 'et', 'se', 'ou', 'of', 'le', 'sa', 've',
'ro', 'ra', 'hi', 'ne', 'me', 'de', 'co', 'ta', 'ec', 'si', 'll',
'so', 'na', 'li', 'la', 'el', 'ma']
def generate_36(word):
  vector_36 = [0 for i in range(36)]
  for char in word:
    if char.isdigit():
      vector_36[ord(char) - ord('0')] = 1
    elif char.isalpha():
      vector_36[10+ord(char) - ord('a')] = 1
  return vector_36

def generate_50(word):
  vector_50 = [0 for i in range(50)]
  for big in bigram:
    if big in word:
      vector_50[bigram.index(big)]=1
  # print("the 50 bigram vector is",vector_50)
  return vector_50


def generate_label(word):
  word = word.lower()
  vector = []
  L = len(word)
  for split in range(2, 6):
    parts = L//split
    for mul in range(split-1):
      vector += generate_36(word[mul*parts:mul*parts+parts])
    vector += generate_36(word[(split-1)*parts:L])

  # diviser le mot word en 2 sous mots ici:
  vector += generate_50(word[0:L//2])
  vector += generate_50(word[L//2: L])
  #   print("la representation phoc de " + word +"est donnée comme suit :",vector)
  # print("################################")  
  return vector


In [ ]:
word="mohammed"
print(generate_label(word))
len(generate_label(word))
# print(sum(generate_label(word)))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

604

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D
from tensorflow.keras.layers import Dense, Flatten,Dropout, BatchNormalization
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.models import Sequential
from keras import losses
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [ ]:
! git clone https://github.com/OmarBoudraa/PUNET

Cloning into 'PUNET'...
remote: Enumerating objects: 148, done.
remote: Total 148 (delta 0), reused 0 (delta 0), pack-reused 148
Receiving objects: 100% (148/148), 58.39 MiB | 12.38 MiB/s, done.
Resolving deltas: 100% (58/58), done.
Updating files: 100% (39/39), done.


In [ ]:
from glob import glob
import cv2
import os
import encodings
from xml.etree import ElementTree as ET
import numpy as np
from datetime import datetime

# WORD_IMAGE_DIR = 'words/'
XML_DIR = './PUNET/xml/'
GW_DIR = './PUNET/images/'
transcripts = {}

def append_data(x, y, transcript, data): # need not return anything
    x.append(data[0])
    y.append(data[1])
    transcript.append(data[2])


def load_data():
    time_start = datetime.now()

    xml_files = glob(XML_DIR+'*.xml')
    print("taille : ",len(xml_files))
    x_train = []
    y_train = []
    train_transcript = []
    x_valid = []
    y_valid = []
    valid_transcript = []
    x_test = []
    y_test = []
    test_transcript = []
    global transcripts
    
    for xml_file in xml_files:
        tree = ET.parse(xml_file)
        root = tree.getroot()
        xml_file_name = os.path.splitext(xml_file)[0]
        print(xml_file_name)
        # Change this code to get the corresponsing word image dir
        # image_dir = xml_file.split('/')[-1].split('.')[0].split('-')
        # image_dir = image_dir[0] + '/' + image_dir[0]+'-'+image_dir[1]+ '/'
        image_dir = GW_DIR # + image_dir

        for word_idx, word_elem in enumerate(root.findall('spot')):
        # for word in root.iter('word'):
            img_id = word_elem.attrib['image'].split('.')[0]
            img_name = image_dir+img_id+'.tif'
            img_transcript = word_elem.attrib['word'].lower()
            #img_transcript = word.get('text').lower()

            im = cv2.imread(img_name, 0)
            #height = np.size(im, 0)
            #print(height)
            x = int(word_elem.attrib['x'])
            y = int(word_elem.attrib['y'])
            h = int(word_elem.attrib['h'])
            w = int(word_elem.attrib['w'])
            img = im[y:y+h,x:x+w]
            #height = np.size(img, 0)
            #print(height)
            if img is None: # Some image files are corrupted
                continue

            target = generate_label(img_transcript)
            if sum(target) == 0: # For special characters
                img_transcript = '' # Use a special notation for them

            img = cv2.resize(img, (100,50))  # phoc requis
            # img = cv2.resize(img, (224,224))   #vgg requis
            img = np.where(img<200, 1, 0)
            img = img[:, :, np.newaxis]

            data = [img, target, img_transcript]
            # print(xml_file_name)
            if xml_file_name == './PUNET/xml/gw_cv1_train' or xml_file_name == './PUNET/xml/gw_cv2_train':
                # print("train --------------")
                append_data(x_train, y_train, train_transcript, data)
            elif xml_file_name == './PUNET/xml/gw_cv3_val':
                append_data(x_valid, y_valid, valid_transcript, data)
            elif xml_file_name == './PUNET/xml/gw_cv4_test':
                append_data(x_test, y_test, test_transcript, data)
            else:
              print("sinon !!")    

    N = len(x_train) + len(x_valid) + len(x_test)

    x_train = np.array(x_train)
    y_train = np.array(y_train)
    train_trainscript = np.array(train_transcript)

    x_valid = np.array(x_valid)
    y_valid = np.array(y_valid)
    valid_transcript = np.array(valid_transcript)

    x_test = np.array(x_test)
    y_test = np.array(y_test)
    test_transcript = np.array(test_transcript)

    print ("Time to fetch data: ", datetime.now() - time_start)

    return (x_train, y_train, train_transcript,
            x_valid, y_valid, valid_transcript,
            x_test, y_test, test_transcript)


In [ ]:
x_train, y_train, train_transcript,x_valid, y_valid, valid_transcript,x_test, y_test, test_transcript = load_data()

taille :  4
./PUNET/xml/gw_cv3_val
./PUNET/xml/gw_cv1_train
./PUNET/xml/gw_cv4_test
./PUNET/xml/gw_cv2_train
Time to fetch data:  0:01:22.660808


In [ ]:
import keras.backend as K
from keras.layers import Layer
# from github avec des changements de tf et th ... 
class SpatialPyramidPooling(Layer):
  
    def __init__(self, pool_list, **kwargs):

        self.dim_ordering = K.image_data_format()
        print(self.dim_ordering)
        assert self.dim_ordering in {'channels_last', 'channels_first'}, 'dim_ordering must be in {tf, th}'

        self.pool_list = pool_list

        self.num_outputs_per_channel = sum([i * i for i in pool_list])

        super(SpatialPyramidPooling, self).__init__(**kwargs)

    def build(self, input_shape):
        if self.dim_ordering == 'channels_first':
            self.nb_channels = input_shape[1]
        elif self.dim_ordering == 'channels_last':
            self.nb_channels = input_shape[3]

    def compute_output_shape(self, input_shape):
        return (input_shape[0], self.nb_channels * self.num_outputs_per_channel)

    def get_config(self):
        config = {'pool_list': self.pool_list}
        base_config = super(SpatialPyramidPooling, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))

    def call(self, x, mask=None):

        input_shape = K.shape(x)

        if self.dim_ordering == 'channels_first':
            num_rows = input_shape[2]
            num_cols = input_shape[3]
        elif self.dim_ordering == 'channels_last':
            num_rows = input_shape[1]
            num_cols = input_shape[2]

        row_length = [K.cast(num_rows, 'float32') / i for i in self.pool_list]
        col_length = [K.cast(num_cols, 'float32') / i for i in self.pool_list]

        outputs = []

        if self.dim_ordering == 'channels_first':
            for pool_num, num_pool_regions in enumerate(self.pool_list):
                for jy in range(num_pool_regions):
                    for ix in range(num_pool_regions):
                        x1 = ix * col_length[pool_num]
                        x2 = ix * col_length[pool_num] + col_length[pool_num]
                        y1 = jy * row_length[pool_num]
                        y2 = jy * row_length[pool_num] + row_length[pool_num]

                        x1 = K.cast(K.round(x1), 'int32')
                        x2 = K.cast(K.round(x2), 'int32')
                        y1 = K.cast(K.round(y1), 'int32')
                        y2 = K.cast(K.round(y2), 'int32')
                        new_shape = [input_shape[0], input_shape[1],
                                     y2 - y1, x2 - x1]
                        x_crop = x[:, :, y1:y2, x1:x2]
                        xm = K.reshape(x_crop, new_shape)
                        pooled_val = K.max(xm, axis=(2, 3))
                        outputs.append(pooled_val)

        elif self.dim_ordering == 'channels_last':
            for pool_num, num_pool_regions in enumerate(self.pool_list):
                for jy in range(num_pool_regions):
                    for ix in range(num_pool_regions):
                        x1 = ix * col_length[pool_num]
                        x2 = ix * col_length[pool_num] + col_length[pool_num]
                        y1 = jy * row_length[pool_num]
                        y2 = jy * row_length[pool_num] + row_length[pool_num]

                        x1 = K.cast(K.round(x1), 'int32')
                        x2 = K.cast(K.round(x2), 'int32')
                        y1 = K.cast(K.round(y1), 'int32')
                        y2 = K.cast(K.round(y2), 'int32')

                        new_shape = [input_shape[0], y2 - y1,
                                     x2 - x1, input_shape[3]]

                        x_crop = x[:, y1:y2, x1:x2, :]
                        xm = K.reshape(x_crop, new_shape)
                        pooled_val = K.max(xm, axis=(1, 2))
                        outputs.append(pooled_val)

        if self.dim_ordering == 'channels_first':
            outputs = K.concatenate(outputs)
        elif self.dim_ordering == 'channels_last':
            #outputs = K.concatenate(outputs,axis = 1)
            outputs = K.concatenate(outputs)
            #outputs = K.reshape(outputs,(len(self.pool_list),self.num_outputs_per_channel,input_shape[0],input_shape[1]))
            #outputs = K.permute_dimensions(outputs,(3,1,0,2))
            #outputs = K.reshape(outputs,(input_shape[0], self.num_outputs_per_channel * self.nb_channels))

        return outputs


In [ ]:
# class BinarizationLayer(Layer):
#     def __init__(self, threshold=0.5, **kwargs):
#         super().__init__(**kwargs)
#         self.threshold = threshold

#     def call(self, inputs):
#         return tf.cast(tf.where(inputs < self.threshold, 0, 1), dtype=tf.float32)

In [ ]:
# layer = BinarizationLayer()
# input = tf.random.normal((1, 10))
# input, layer(input)

(<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
 array([[ 2.1678388 , -0.03977485, -1.6608976 , -0.7378837 ,  0.15050058,
         -0.50202596,  0.8265431 ,  0.10619392,  0.42880473, -0.656575  ]],
       dtype=float32)>,
 <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[1., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)>)

In [ ]:
# def func(x):
#     greater = K.greater_equal(x, 0.5) #will return boolean values
#     greater = K.cast(greater, dtype=K.floatx()) #will convert bool to 0 and 1    
#     return greater

In [ ]:
# from keras.layers import Lambda

In [ ]:
model = Sequential()
model.add(Conv2D(64, (3, 3), padding='same',
          activation='relu', input_shape=(50,100,1)))
model.add(Conv2D(64, (3, 3), padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2), strides=2))
model.add(Conv2D(128, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(128, (3, 3), padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2), strides=2))
model.add(Conv2D(256, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(256, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(256, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(256, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(256, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(256, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(512, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(512, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(512, (3, 3), padding='same', activation='relu'))
model.add(SpatialPyramidPooling([1, 2, 4]))
model.add(Dense(4096, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(4096, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(604, activation='sigmoid'))
# model.add(
#     Lambda(func)
# )
#model.add(BinarizationLayer(trainable=False))
## arcitecture facile à comprendre et à programmer avec keras 

channels_last


In [ ]:
loss = losses.binary_crossentropy
optimizer = SGD(lr=1e-4, momentum=.9, decay=5e-5)
model.compile(loss=loss, optimizer=optimizer, metrics=[
    tf.keras.metrics.CosineSimilarity(),tf.keras.metrics.BinaryAccuracy(threshold = 0.1)
    ])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 50, 100, 64)       640       
                                                                 
 conv2d_1 (Conv2D)           (None, 50, 100, 64)       36928     
                                                                 
 max_pooling2d (MaxPooling2D  (None, 25, 50, 64)       0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 25, 50, 128)       73856     
                                                                 
 conv2d_3 (Conv2D)           (None, 25, 50, 128)       147584    
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 12, 25, 128)      0         
 2D)                                                    

/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/gradient_descent.py:108: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


In [ ]:
hist_phocnet=model.fit(x_train,y_train,batch_size=15,epochs=30,validation_data=(x_valid, y_valid))

Epoch 1/30
162/162 [==============================] - 26s 85ms/step - loss: 0.6931 - cosine_similarity: 0.1670 - binary_accuracy: 0.0300 - val_loss: 0.6930 - val_cosine_similarity: 0.1683 - val_binary_accuracy: 0.0305
Epoch 2/30
162/162 [==============================] - 13s 80ms/step - loss: 0.6929 - cosine_similarity: 0.1670 - binary_accuracy: 0.0300 - val_loss: 0.6929 - val_cosine_similarity: 0.1683 - val_binary_accuracy: 0.0305
Epoch 3/30
162/162 [==============================] - 12s 74ms/step - loss: 0.6928 - cosine_similarity: 0.1670 - binary_accuracy: 0.0300 - val_loss: 0.6927 - val_cosine_similarity: 0.1683 - val_binary_accuracy: 0.0305
Epoch 4/30
162/162 [==============================] - 13s 81ms/step - loss: 0.6927 - cosine_similarity: 0.1670 - binary_accuracy: 0.0300 - val_loss: 0.6926 - val_cosine_similarity: 0.1683 - val_binary_accuracy: 0.0305
Epoch 5/30
162/162 [==============================] - 12s 74ms/step - loss: 0.6926 - cosine_similarity: 0.1670 - binary_accuracy

In [ ]:
# y_pred = model.predict(x_test)
# y_pred = np.where(y_pred<0.5, 0, 1)
# # x_test[0]
y_pred

array([[0.00723306, 0.02719549, 0.01333661, ..., 0.00973689, 0.0147216 ,
        0.00558952],
       [0.00840291, 0.02962407, 0.01478983, ..., 0.01062724, 0.01639656,
        0.0063326 ],
       [0.00066896, 0.00501959, 0.0017162 , ..., 0.00106058, 0.00195517,
        0.00047366],
       ...,
       [0.00429608, 0.01882279, 0.00842623, ..., 0.00585556, 0.00929966,
        0.003205  ],
       [0.00584107, 0.0232419 , 0.010988  , ..., 0.00797388, 0.01224659,
        0.00435337],
       [0.00056179, 0.00439022, 0.00145295, ..., 0.00085925, 0.00161612,
        0.00039869]], dtype=float32)

In [ ]:
score = model.evaluate(x_test, y_test, verbose = 0) 
print(score)
print('Test loss:', score[0]) 
print('Test accuracy:', score[1])

[0.10543923825025558, 0.3644101917743683]
Test loss: 0.10543923825025558
Test accuracy: 0.3644101917743683


In [ ]:
y_pred = model.predict(x_test)
y_pred = np.where(y_pred<0.5, 0, 1)
transcripts=test_transcript
# start = datetime.now() 
N = len(transcripts)
precision = {}
count = {}
for i in range(N):
  if transcripts[i] not in precision.keys():
    precision[transcripts[i]] = 1
    count[transcripts[i]] = 0
  else:
    precision[transcripts[i]] += 1

for i in range(N):
  pred = y_pred[i]
  acc = np.sum(abs(y_test-pred), axis=1)
  tmp = np.argmin(acc)
  if transcripts[tmp] == transcripts[i]:
    count[transcripts[tmp]] += 1

mean_avg_prec = [0, 0]
for i in range(N):
  if precision[transcripts[i]] <= 1:
    continue
  mean_avg_prec[0] += count[transcripts[i]]*1.0/precision[transcripts[i]] 
  mean_avg_prec[1] += 1
result= 1.-(mean_avg_prec[0]*1./mean_avg_prec[1])
# print ("Time taken to calculate l2 dist: ", datetime.now() - start)
print ("The Mean Average Precision = ", result)
print ("Total test cases = ", N)

38/38 [==============================] - 1s 35ms/step
The Mean Average Precision =  0.9759036144578314
Total test cases =  1215


In [ ]:
model.save("phocnet_word_spotting_best_model.h5")

In [ ]:
tf.keras.backend.clear_session()